apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/GiorgosThf/k8s-platform.git
    targetRevision: master
    path: clusters/prod/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true